export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const ADD_POLDY_COMPANY_SUCCESS = "ADD_POLDY_COMPANY_SUCCESS";

export const ADD_COMPANY_SUCCESS ="ADD_COMPANY_SUCCESS";